version: "3.8"

services:
  mongodb-books-db:
    container_name: database
    image: mongo:6.0.2-focal
    environment:
      MONGO_INITDB_DATABASE: library
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
    restart: unless-stopped

  flask-books-backend:
    container_name: backend
    build: ./backend
    ports:
      - 5000:${BACKEND_PORT}
    depends_on:
      - mongodb-books-db
    environment:
      APP_DEBUG: "True"
      APP_PORT: ${BACKEND_PORT}
      MONGODB_DATABASE: library
      MONGODB_HOSTNAME: mongodb-books-db
    networks:
      - backend
      - frontend
    restart: unless-stopped

  vue-books-frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        - API_URL=${BACKEND_PORT}
    ports:
      - 8000:8080
    depends_on:
      - flask-books-backend

    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
